# Cloud CV - Jekyll Configuration
# SRE/DevOps Engineer Portfolio

# Site settings
title: "SRE/DevOps Engineer - Cloud CV"
description: "15+ years of experience in cloud infrastructure, automation, and site reliability engineering"
author: "SRE/DevOps Engineer"
email: "your.email@example.com"
url: "https://l4linux.com/resume"
baseurl: "/resume"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO and social
twitter:
  username: your_twitter_handle
  card: summary_large_image

github:
  username: your_github_username

linkedin:
  username: your_linkedin_username

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  experience:
    output: true
    permalink: /experience/:name/
  certifications:
    output: true
    permalink: /certifications/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "experience"
    values:
      layout: "experience"
  - scope:
      path: ""
      type: "certifications"
    values:
      layout: "certification"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - README.md
  - package.json
  - package-lock.json
  - docker/
  - infra/
  - scripts/
  - docs/

# Include
include:
  - _pages

# Sass settings
sass:
  style: compressed

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Timezone
timezone: UTC

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Feed
feed:
  limit: 10

# Sitemap
sitemap:
  changefreq: weekly
  priority: 0.5
  lastmod: true
