# Cloud CV - Prometheus Configuration
# Monitoring configuration for SRE/DevOps Engineer Portfolio

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Nginx metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:9113']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node exporter (if used)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Cloud CV application metrics
  - job_name: 'cloud-cv'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /metrics
    scrape_interval: 10s

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 15s

  # Custom metrics endpoint
  - job_name: 'custom-metrics'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: /api/metrics
    scrape_interval: 30s
